# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPriceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price_in_pennies', models.PositiveIntegerField()),
                ('percentage_change', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='pastpricerecords',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='external_product_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='PastPriceRecords',
        ),
        migrations.AddField(
            model_name='pastpricerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Product'),
        ),
    ]
